# Generated by Django 4.1.7 on 2023-02-21 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import menu.models
import menu.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_store', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('phone_store', models.IntegerField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('banner_image', models.ImageField(blank=True, upload_to=menu.models.nameFile, validators=[menu.validators.validate_banner_size_kb])),
                ('profile_image', models.ImageField(blank=True, upload_to=menu.models.nameFile, validators=[menu.validators.validate_banner_size_kb])),
                ('barcode', models.ImageField(blank=True, upload_to=menu.models.nameFile)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, upload_to='<function nameFile at 0x10720dbd0>/products', validators=[menu.validators.validate_image_size_kb])),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ingredients', models.TextField(max_length=400)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='menu.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_id', to='menu.owner')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.owner'),
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='+', to='menu.product'),
        ),
    ]
