# Generated by Django 4.1.7 on 2023-02-24 17:04

from django.db import migrations, models
import menu.validators


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='phone_store',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='<function nameFile at 0x7f95a71f3c70>/products', validators=[menu.validators.validate_image_size_kb]),
        ),
    ]
