# Generated by Django 4.1.7 on 2023-02-24 17:49

from django.db import migrations, models
import menu.validators


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_owner_phone_store_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='<function nameFile at 0x7fb277fbbc70>/products', validators=[menu.validators.validate_image_size_kb]),
        ),
    ]
