# Generated by Django 4.1.7 on 2023-02-28 19:17

from django.db import migrations, models
import menu.validators


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_owner_created_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='<function nameFile at 0x7fe5990fba30>/products', validators=[menu.validators.validate_image_size_kb]),
        ),
    ]
