# Generated by Django 4.1.7 on 2023-03-02 19:31

from django.db import migrations, models
import menu.validators


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='<function nameFile at 0x7f1b5273ba30>', validators=[menu.validators.validate_image_size_kb]),
        ),
    ]
