# Generated by Django 4.1.7 on 2023-03-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
