# Generated by Django 4.1.7 on 2023-03-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='banner_image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name_store',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone_store',
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='profile_image',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
